pihole:
  serviceWeb:
    type: ClusterIP

  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - "pihole.lan"
  serviceDns:
    loadBalancerIP: 192.168.178.25
    type: LoadBalancer

  # DNS1: "8.8.8.8"