apiVersion: apps/v1
kind: Deployment
metadata:
  name: rowsflix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rowsflix
  template:
    metadata:
      labels:
        app: rowsflix
    spec:
      containers:
        - name: rowsflix
          image: ajugeorge97/rowsflix:1.1.2
          envFrom:
            - secretRef:
                name: rowsflix-secret   # 👈 kubectl create secret generic rowsflix-secret --from-env-file=.env
          volumeMounts:
            - name: sessions
              mountPath: /app/sessions
            - name: media
              mountPath: /media
      volumes:
        - name: sessions
          emptyDir: {}
        - name: media
          hostPath:
            path: /data/jellyfin
            type: Directory
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
---
apiVersion: v1
kind: Secret
metadata:
  name: rowsflix-secret
type: Opaque