argo-cd:
  configs:
    params:
      server.insecure: true
  namespaceOverride: "argo"
  global:
    domain: argocd.ajugeorge.com
    nodeSelector:
      kubernetes.io/hostname: hp-server
    tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "experiments"
        effect: "NoSchedule"
  server:
    ingress:
      hostname: argocd.ajugeorge.com
      tls: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
      enabled: true
      ingressClassName: traefik
