persistence:
  config:
    hostPath: /data/homeassistant/config
    type: DirectoryOrCreate
    size: 5Gi

homeassistant:
  replicaCount: 1
  controller:
    type: Deployment

  deploymentStrategy: Recreate

  hostNetwork: false
  dnsPolicy: ClusterFirst

  ingress:
    enabled: true
    annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
    className: traefik
    hosts:
      - host: homeassistant.ajugeorge.com
        paths:
          - path: /
            pathType: Prefix

  resources:
    requests:
      memory: 1Gi
    limits:
      memory: 2Gi

  persistence:
    enabled: true
    existingClaim: homeassistant-config
