jellyfin:
  ingress:
    enabled: true
    hosts:
      - host: jellyfin.lan
        paths:
          - path: /
            pathType: Prefix

  persistence:
    media:
      type: hostPath
      hostPath: "/data/jellyfin"
