jellyfin:
  image:
    repository: docker.io/jellyfin/jellyfin
    tag: "10.11.11"

  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    fsGroupChangePolicy: OnRootMismatch
    seccompProfile:
      type: RuntimeDefault

  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    runAsNonRoot: true

  ingress:
    enabled: true
    className: traefik
    hosts:
      - host: jellyfin.lan
        paths:
          - path: /
            pathType: Prefix
      - host: homelab.taileac0a9.ts.net
        paths:
          - path: /jellyfin
            pathType: Prefix

  persistence:
    media:
      type: hostPath
      hostPath: "/data/jellyfin"

  resources:
    requests:
      memory: "2Gi"
      cpu: "500m"
    limits:
      memory: "4Gi"
      cpu: "2"
