apiVersion: v1
kind: PersistentVolume
metadata:
  name: homeassistant-config
spec:
  capacity:
    storage: {{ .Values.persistence.config.size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: homeassistant-hostpath
  hostPath:
    path: {{ .Values.persistence.config.hostPath | quote }}
    type: {{ .Values.persistence.config.type }}

